//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace aspAura.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class aspAuraEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new aspAuraEntities object using the connection string found in the 'aspAuraEntities' section of the application configuration file.
        /// </summary>
        public aspAuraEntities() : base("name=aspAuraEntities", "aspAuraEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new aspAuraEntities object.
        /// </summary>
        public aspAuraEntities(string connectionString) : base(connectionString, "aspAuraEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new aspAuraEntities object.
        /// </summary>
        public aspAuraEntities(EntityConnection connection) : base(connection, "aspAuraEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Todo> Todoes
        {
            get
            {
                if ((_Todoes == null))
                {
                    _Todoes = base.CreateObjectSet<Todo>("Todoes");
                }
                return _Todoes;
            }
        }
        private ObjectSet<Todo> _Todoes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Todoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTodoes(Todo todo)
        {
            base.AddObject("Todoes", todo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspAuraModel", Name="Todo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Todo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Todo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="content">Initial value of the content property.</param>
        /// <param name="done">Initial value of the done property.</param>
        public static Todo CreateTodo(global::System.Int32 id, global::System.String content, global::System.Boolean done)
        {
            Todo todo = new Todo();
            todo.id = id;
            todo.content = content;
            todo.done = done;
            return todo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean done
        {
            get
            {
                return _done;
            }
            set
            {
                OndoneChanging(value);
                ReportPropertyChanging("done");
                _done = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("done");
                OndoneChanged();
            }
        }
        private global::System.Boolean _done;
        partial void OndoneChanging(global::System.Boolean value);
        partial void OndoneChanged();

        #endregion
    
    }

    #endregion
    
}
